# Generated by Django 3.1.6 on 2021-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertable',
            name='student_roll',
            field=models.IntegerField(default=0),
        ),
    ]
