# Generated by Django 3.1.6 on 2021-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teachertable_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachertable',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
